CREATE TABLE "employee" (
	"ID"	INTEGER NOT NULL,
	"NAME"	TEXT NOT NULL UNIQUE,
	"AGE"	INTEGER NOT NULL,
	"ADDRESS"	TEXT,
	"SALARY"	REAL DEFAULT 0,
	PRIMARY KEY("ID" AUTOINCREMENT)
);


INSERT INTO employee (NAME,AGE,ADDRESS,SALARY)
VALUES ('Paul', 32, 'California', 20000.00 );
INSERT INTO employee (NAME,AGE,ADDRESS,SALARY)
VALUES ('Allen', 25, 'Texas', 15000.00 );
INSERT INTO employee (NAME,AGE,ADDRESS,SALARY)
VALUES ('Teddy', 23, 'Norway', 20000.00 );
INSERT INTO employee (NAME,AGE,ADDRESS,SALARY)
VALUES ('Mark', 25, 'Rich-Mond ', 65000.00 );
INSERT INTO employee (NAME,AGE,ADDRESS,SALARY)
VALUES ('David', 27, 'Texas', 85000.00 );
INSERT INTO employee (NAME,AGE,ADDRESS,SALARY)
VALUES ('Kim', 22, 'South-Hall', 45000.00 );
INSERT INTO employee (NAME,AGE,ADDRESS,SALARY)
VALUES ('James', 24, 'Houston', 10000.00 );